spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=postgres
# Coloque aqui a senha que você escolheu na instalação!
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update